export default {
  font: {
    family: {
      primary: 'Lato',
      secondary: 'Titillium Web',
    },
    size: {
      xsmaller: '1rem',
      smaller: '1.1rem',
      xxxsmall: '1.2rem',
      xxsmall: '1.4rem',
      xsmall: '1.44rem',
      small: '1.557rem',
      regular: '1.6rem',
      large: '1.8rem',
      xlarge: '2rem',
      xxlarge: '2.3rem',
      xxxlarge: '2.4rem',
      larger: '2.8rem',
    },
  },
  color: {
    white: '#fff',
    bg: '#dedede',
    green: '#7ebc43',
    chardonnay: '#00b495',
    highlight: '#f79552',
    redViolet: '#d14b8f',
    pink: '#ef58ad',
    lightGrey: '#555',
    silver: '#ccc',
    grey: '#666',
    darkGrey: '#888',
    blackMetal: '#1d1d1b',
    darkestGrey: '#111',
    black: '#000',
  },
  layers: {
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
} as const;
