name: Verify PR
on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Node setup
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Install dependencies
          run: npm install

        - name: Lint 
          run: npm run lint

        - name: Test
          run: npm run test:ci

        - name: Build
          run: npm run build
